[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fabrictestbed-extensions"
dynamic = ["version"]
description = "FABRIC Python Client Library and CLI Extensions"
authors = [
    {name="Paul Ruth", email="pruth@renci.org"},
    {name="Komal Thareja", email="kthare10@renci.org"}
]
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE" }
requires-python = '>=3.9'
dependencies = [
    "build",
    "ipycytoscape",
    "ipywidgets",
    "ipyleaflet",
    "ipycytoscape",
    "tabulate",
    "fabrictestbed==1.3.1",
    "paramiko",
    "jinja2>=3.0.0",
    "pandas",
    "numpy",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://fabric-testbed.net/"
Sources = "https://github.com/fabric-testbed/fabrictestbed-extensions"
Documentation = "https://fabric-fablib.readthedocs.io/"
ChangeLog = "https://github.com/fabric-testbed/fabrictestbed-extensions/blob/main/CHANGELOG.md"

[project.optional-dependencies]
doc = ["sphinx", "furo"]
