# Run some code checks with GitHub Actions.

name: Code checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # See https://black.readthedocs.io/en/stable/integrations/github_actions.html
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "~= 22.0"
