# Run some code checks with GitHub Actions.

name: Code checks

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # since we need to diff against origin/main.

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'  # cache pip dependencies
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black

      - name: Run "black --check"
        run: |
          python -m black --check --verbose .

      # Remind PR authors to update CHANGELOG.md
      - name: Check that Changelog has been updated
        if: github.event_name != 'pull_request'
        run: |
          git diff --exit-code "origin/${GITHUB_BASE_REF}" -- CHANGELOG.md
          if [ $? -eq 0 ]; then
              echo "Please update CHANGELOG.md"
              exit 1
          fi
