# FABRIC policy requires that code commits are signed with the
# committer's GPG key.
#
# https://github.com/marketplace/actions/check-signed-commits-in-pr
# runs on pull_request_target events.

name: Check signed commits in PR
on: pull_request_target

jobs:
  check-signed-commits:
    name: Check signed commits in PR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # Allow 1Password/check-signed-commits-action to leave comments
      # on pull requests.
      pull-requests: write

    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
