name: Check docstring coverage

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'  # cache pip dependencies
          cache-dependency-path: pyproject.toml

      - name: Install interrogate
        run: |
          python -m pip install --upgrade pip
          python -m pip install interrogate==1.7.0

      - name: Check docstring coverage with interrogate
        run: |
          python -m interrogate -vv fabrictestbed_extensions
