# Publish the package on PyPI.
#
# https://pypi.org/project/fabrictestbed-extensions/ is configured
# with GitHub as "trusted publisher", meaning, there is no exchange of
# a long-term password or token between GitHub and PyPI.  See
# documentation here: https://docs.pypi.org/trusted-publishers/

name: Publish

# This workflow will be triggered when a tag with prefix "rel" is
# pushed to the repository.
on:
  push:
    tags:
      - "rel*"

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  pypi-publish:
    name: Publish packages on PyPI
    runs-on: ubuntu-latest
    needs:
      - tests

    environment:
      name: publish
      url: https://pypi.org/p/fabrictestbed-extensions

    # This permission is mandatory for trusted publishing.
    permissions:
      id-token: write

    steps:
      - name: Check out sources
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install flit
          python -m flit build

      # See https://github.com/marketplace/actions/pypi-publish.
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
